using System.Collections.Generic;

namespace MSZpevnik
{
	partial class Search
	{
		public Search()
		{
			allSongs = new List<SongData>();
			allSongs.Add(new SongData("CH6", "Chvalte služebníci", "CH6.png"));
			allSongs.Add(new SongData("CH1", "Chci oslavovat", "CH1.png"));
			allSongs.Add(new SongData("H2", "Hledám Tvoji tvář", "H2.png"));
			allSongs.Add(new SongData("H3", "Hosana zní", "H3.png"));
			allSongs.Add(new SongData("H6", "Hospodin je král", "H6"));
			allSongs.Add(new SongData("CH2", "Chci, pane, chválit Tě", "CH2.png"));
			allSongs.Add(new SongData("H1", "Haleluja, všichni zpívají", "H1.png"));
			allSongs.Add(new SongData("CH3", "Chleba a víno neseme", "CH3.png"));
			allSongs.Add(new SongData("H5", "Hospodin je můj pastýř", "H5.png"));
			allSongs.Add(new SongData("H4", "Hosana", "H4.png"));
			allSongs.Add(new SongData("CH4", "Chvalospěv", "CH4.png"));
			allSongs.Add(new SongData("CH5", "Chvalte hospodina", "CH5.png"));
			allSongs.Add(new SongData("B2", "Bůh buď v hlavě mé", "B2.png"));
			allSongs.Add(new SongData("A2", "Aleluja", "A2.png"));
			allSongs.Add(new SongData("A6", "Alleluja spasení", "A6"));
			allSongs.Add(new SongData("A5", "Ať srdce mé Tebe vídá", "A5.png"));
			allSongs.Add(new SongData("B1", "Boží beránku", "B1.png"));
			allSongs.Add(new SongData("B4", "Byl člověk jako já", "B4.png"));
			allSongs.Add(new SongData("B3", "Bůh je síla má", "B3.png"));
			allSongs.Add(new SongData("A3", "Apoštolská", "A3.png"));
			allSongs.Add(new SongData("A1", "Abraham", "A1.png"));
			allSongs.Add(new SongData("A4", "Ať požehnán je Bůh", "A4.png"));
			allSongs.Add(new SongData("S1", "Skrze něj", "S1.png"));
			allSongs.Add(new SongData("S3", "Svatý", "S3.png"));
			allSongs.Add(new SongData("S5", "Studna", "S5.png"));
			allSongs.Add(new SongData("R1", "Řeka Tvé lásky", "R1.png"));
			allSongs.Add(new SongData("S4", "Svatý je Pán, hosana", "S4.png"));
			allSongs.Add(new SongData("S2", "Spoj nás v jedno", "S2.png"));
			allSongs.Add(new SongData("K2", "Kéž se v našich domech tančí", "K2.png"));
			allSongs.Add(new SongData("K4", "Kde se křesťané", "K4"));
			allSongs.Add(new SongData("K3", "Králi, milost nám dej", "K3.png"));
			allSongs.Add(new SongData("K1", "Každý den", "K1.png"));
			allSongs.Add(new SongData("K5", "Ke slávě tvé", "K5"));
			allSongs.Add(new SongData("J2", "Ježíš je Pán pánů", "J2.png"));
			allSongs.Add(new SongData("J3", "Jsme děti tvé", "J3.png"));
			allSongs.Add(new SongData("E2", "Eucharistia", "E2.png"));
			allSongs.Add(new SongData("D4", "Dobrořeč duše má", "D4.png"));
			allSongs.Add(new SongData("D2", "Dej chléb, víno na oltář", "D2.png"));
			allSongs.Add(new SongData("D1", "David a Goliáš", "D1.png"));
			allSongs.Add(new SongData("E1", "Effatha", "E1.png"));
			allSongs.Add(new SongData("D6", "Duch a nevěsta", "D6.png"));
			allSongs.Add(new SongData("D3", "Dnes jdu k Tobě", "D3.png"));
			allSongs.Add(new SongData("T7", "Tobě králi toužím", "T7.png"));
			allSongs.Add(new SongData("T5", "Tví jsme my", "T5.png"));
			allSongs.Add(new SongData("T1", "To je Tvůj dům", "T1.png"));
			allSongs.Add(new SongData("T9", "Ty jsi jediný Bůh", "T9.png"));
			allSongs.Add(new SongData("T3", "Objevit točnu", "T3.png"));
			allSongs.Add(new SongData("T4", "Objevit lásku", "T4.png"));
			allSongs.Add(new SongData("T11", "Ty jsi mi vším", "T11.png"));
			allSongs.Add(new SongData("T12", "Ty jsi pánem všech mých dní", "T12.png"));
			allSongs.Add(new SongData("T2", "Tobě patří chvála", "T2.png"));
			allSongs.Add(new SongData("T6", "Tvoje jméno vyznávám", "T6.png"));
			allSongs.Add(new SongData("T8", "Tvůj plamen", "T8.png"));
			allSongs.Add(new SongData("T10", "Ty jsi král", "T10.png"));
			allSongs.Add(new SongData("04", "Svatý, Svatý", "04.png"));
			allSongs.Add(new SongData("03", "Věřím v jednoho Boha", "03.png"));
			allSongs.Add(new SongData("01", "Pane, náš Bože", "01.png"));
			allSongs.Add(new SongData("05", "Beránku Boží", "05.png"));
			allSongs.Add(new SongData("02", "Sláva na výsostech Bohu", "02.png"));
			allSongs.Add(new SongData("Z7", "Zpívej haleluja Pánu", "Z7.png"));
			allSongs.Add(new SongData("Z3", "Zář tváře Tvé", "Z3.png"));
			allSongs.Add(new SongData("Z2", "Za dílo Tvé", "Z2.png"));
			allSongs.Add(new SongData("Z8", "Zvěstuj dál Boží lásku", "Z8.png"));
			allSongs.Add(new SongData("Z1", "Z lásky", "Z1.png"));
			allSongs.Add(new SongData("Z4", "Zdař Bůh", "Z4.png"));
			allSongs.Add(new SongData("Z6", "Zpívej Haleluja", "Z6.png"));
			allSongs.Add(new SongData("Z5", "Zde jsem", "Z5.png"));
			allSongs.Add(new SongData("V3", "Vyvyšuji Tebe Pane", "V3.png"));
			allSongs.Add(new SongData("V11", "Veď me stále blíž", "V11"));
			allSongs.Add(new SongData("V9", "Vzdejme Pánu díky", "V9.png"));
			allSongs.Add(new SongData("V2", "Větší je náš Bůh", "V2.png"));
			allSongs.Add(new SongData("V5", "Všichni jsme jedno tělo", "V5.png"));
			allSongs.Add(new SongData("V10", "V smělé důvěře", "V10"));
			allSongs.Add(new SongData("V3", "Víc lásky", "V3.png"));
			allSongs.Add(new SongData("V1", "V ten den, kdy Pán", "V1.png"));
			allSongs.Add(new SongData("V4", "Vodo života", "V4.png"));
			allSongs.Add(new SongData("V8", "Vzdej dík", "V8.png"));
			allSongs.Add(new SongData("V7", "Vzácný jsi", "V7.png"));
			allSongs.Add(new SongData("M2", "Mojžíš", "M2.png"));
			allSongs.Add(new SongData("M3", "Můj Bůh je můj štít", "M3.png"));
			allSongs.Add(new SongData("N1", "Nade mnou se smiluj", "N1.png"));
			allSongs.Add(new SongData("M5", "Moc tvé lásky", "M5"));
			allSongs.Add(new SongData("M4", "Můj králi, má spáso", "M4.png"));
			allSongs.Add(new SongData("M1", "Mé dlaně zvednuté", "M1.png"));
			allSongs.Add(new SongData("M6", "Majesty Sláva tvá", "M6.png"));
			allSongs.Add(new SongData("N4", "Nyní pokloňme se před králem", "N4.png"));
			allSongs.Add(new SongData("N2", "Nám, Pane, dal jsi slovo své", "N2.png"));
			allSongs.Add(new SongData("N3", "Neseme, Pane, chléb a víno", "N3.png"));
			allSongs.Add(new SongData("O2", "Odpusť", "O2.png"));
			allSongs.Add(new SongData("O1", "Ó Bože, světlo naše", "O1.png"));
			allSongs.Add(new SongData("O4", "Otevřme písmo", "O4.png"));
			allSongs.Add(new SongData("O3", "Otče náš", "O3.png"));
			allSongs.Add(new SongData("P3", "Pařížská hymna", "P3.png"));
			allSongs.Add(new SongData("P5", "Pojď - svatební text", "P5.png"));
			allSongs.Add(new SongData("P8", "Požehnaný jsi Bože", "P8.png"));
			allSongs.Add(new SongData("P2", "Pane, přijď s mocí svou", "P2.png"));
			allSongs.Add(new SongData("P15", "Příjď tvůj oheň", "P15"));
			allSongs.Add(new SongData("P14", "Pane můj ty jediný", "P14"));
			allSongs.Add(new SongData("P6", "Pojď, teď je ten čas jej chválit", "P6.png"));
			allSongs.Add(new SongData("P12", "Přijmi, Pane", "P12.png"));
			allSongs.Add(new SongData("P1", "Pane Bože přijď k nám", "P1.png"));
			allSongs.Add(new SongData("P4", "Píseň spasených", "P4.png"));
			allSongs.Add(new SongData("P9", "Právě teď ", "P9.png"));
			allSongs.Add(new SongData("P13", "Přiznej Pánu jeho moc a čest", "P13.png"));
			allSongs.Add(new SongData("P11", "Přijď, přijď, duchu boží", "P11.png"));
			allSongs.Add(new SongData("P10", "Přijď, duchu svatý, k nám", "P10.png"));
			allSongs.Add(new SongData("P7", "Požehnaný", "P7.png"));
		}
	};
}
